### ISSUE TITLE
Elasticsearch 2.0

### ISSUE THREAD

**Issue by brizzbane** [Asquera/elasticsearch-http-basic#62] opened 2015-11-03 17:17 UTC
any plans to make compatible with 2.0?

**Comment by Xylakant** [comment] 2015-11-03 17:23
no, currently not since we're not running ES 2.0 anywhere (yet). We'd accept a PR if someone is willing to provide one.

**Comment by defunctzombie** [comment] 2016-01-01 19:44
Will it not work out of the box with ES v2?

**Comment by n0mer** [comment] 2016-01-03 23:18
+1 for v2.0 compatibility - what breaks (if any) ?

**Comment by kira-42** [comment] 2016-01-04 03:50
This is what I'm getting - ES version 2.1.1 on Ubuntu
java.lang.IllegalStateException: Unable to initialize plugins
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:111)
        at org.elasticsearch.node.Node.<init>(Node.java:146)
        at org.elasticsearch.node.Node.<init>(Node.java:128)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.nio.file.FileSystemException: /usr/share/elasticsearch/plugins/elasticsearch-http-basic-1.5.1.jar/plugin-descriptor.properties: Not a directory
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:317)
        at java.nio.file.Files.newByteChannel(Files.java:363)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:380)
        at java.nio.file.Files.newInputStream(Files.java:108)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:302)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:108)
        ... 6 more

**Comment by kbokarius** [comment] 2016-01-04 23:59
+1 for this

**Comment by Xylakant** [comment] 2016-01-05 08:11
We are currently not actively developing features for this project. ES 2.0 changed various internal APIs, so this would need some overhaul to make it work.

We'd be willing to review and accept a PR that adds 2.0 compat.

**Comment by n0mer** [comment] 2016-01-06 02:21
@Xylakant can you start from creating plugin-descriptor.properties ?

**Comment by Xylakant** [comment] 2016-01-06 11:15
I'll repeat: We are currently not actively developing features for this project. We're not using this plugin internally. This actually started out as a POC against some 0.90 version of ES and the only reason we're still keeping this around is that people started using it. We provide support and development on a best-effort basis, that is when the people involved here do have time to do so. Currently we don't have any resources to assign to porting the codebase to 2.0. We might get around to do that at some point, but until then all we can provide is a review and merge a pull request.

**Comment by vionemc** [comment] 2016-01-27 13:56
+1 for this

**Comment by Xylakant** [comment] 2016-01-27 13:59
@vionemc as said before, we're not doing any active development at the moment. If you want 2.0 compat you'll have to provide a patch.

**Comment by vionemc** [comment] 2016-01-27 14:04
@Xylakant I know. Just letting you know there are demands.

**Comment by Xylakant** [comment] 2016-01-27 14:07
You're creating noise. We know there's demand, but this is a free offer that we finance from other work we do. We currently don't have time, so there's no offer. Adding a thousand +1 will not change that, it just fills the mailbox of everybody who's involved in this project. Please only add comments that provide value - for example a patch.

**Comment by vionemc** [comment] 2016-01-27 14:08
@Xylakant okay, I am sorry

**Comment by n0mer** [comment] 2016-01-27 23:00
@Xylakant i'll just leave this here http://blog.clojurewerkz.org/blog/2013/04/20/how-to-make-your-open-source-project-really-awesome/

**Comment by skade** [comment] 2016-01-28 04:08
Hi @n0mer,

While I agree that the clojurewerkz team is doing a great job at this, but them them saying that anything less then the things they describe is a bit much. I'm not interested in running a mailing list for a meager plugin. But that's not the core of the issue. The core of the issue is:

```
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE...
```

I take that very seriously. You are free to do anything with this plugin, but don't expect anything from me.

elasticsearch-http-basic is a project that was created by me to try out what the Elasticsearch Plugin API can do and how it works. Part of that was checking the release process. It never actually ended up in production for any of my projects. It is, however, released to our best knowledge to be used in production for any version that it is released on. But it is, in the end, PROVIDED "AS IS". No guarantee for future development, especially not major version bumps of the base technology.

In addition do that, the ES plugin API is volatile and creates a non-trivial amount of work between versions.

This is still the state of the project: it is maintained by us as a best effort, though we are not using it. We review patches on need. We do also provide commit access to those wishing to maintain it - but no one ever did so beyond the release they needed.

So, here's the thing: Someone will port the project once we have some time for this (beyond work for other OS and Community projects we are involved in). This is non-trivial, as we have no use for this project.

What really nags me is that people seem to believe that we owe them anything because I coded some useful stuff 4 years ago and made it available to them free of charge. I'll consider that before open-sourcing something else.

You are all still welcome to use this piece of software, evolve it, rip it apart, reassemble it, use it as a reference, collaborate on it, be involved in it and run your business on top of it. But I don't owe you one hour, because:

```
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE...
```

Still waiting for "How to make your usage of other peoples work really awesome" to be written.

Florian

**Comment by stevegraham** [comment] 2016-01-28 04:19
#REKT

**Comment by n0mer** [comment] 2016-01-28 04:58
@Xylakant please do not be offended - i posted this article as a suggestion, not as a complaint.

open-sourcing is great idea, cool that it works for ES 1.x

I personally moved to AWS ES offering, they obviously do not allow any plugins.

**Closed** 2017-11-02 10:26 UTC
